### ISSUE TITLE
[Documentation] EPIC - Update Intro to CNFs slides for Mobile World Congress (Feb 25-28, 2019)

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#170]
[Documentation] Update Intro to CNFs slides for Mobile World Congress 
---

### Short description: update Intro to Cloud-native Network Functions slides from KubeCon Seattle for MWC presentation

- Event dates: Feb 25-28, 2019
- Audience: Executives, managers

New items to add to slides: 
---
- [x] Add slide for: Block diagrams for how to install Kubernetes #178 

- [x] Add slide for: Block diagrams for Kubernetes environment components #177 

- [x] Add slide for: Open source OpenStack solution for dataplane NF testing 

- [x] Add slide for: Block diagrams for how to install OpenStack solution #180 

- [x] Add slide for: Block diagrams for OpenStack environment components #179 

   - [x] Add follow-up slide for: oval around boxes (cluster) w/ “Soon to be replaced by kubeadm”

- [x] Add slide for: Snake case scenario - what does this do?

- [x] Add slide for: What's next "use kubeadmn when bootstrapping K8s"

- [x] Add slide for: What's next "Few sentences summarizing of ideal, future test cases, ie segmented routing" 

- [x] Add slide for: CNF BoF - how to get involved 
  - Join CNF BoF meetings: First and Third Wednesdays at 16:00-17:00 UTC
  - Subscribe to Mailing List: (URL needed) 
  - Join cncf.io slack channel "#cnf"
