### ISSUE TITLE
Update VPP-based IP router OpenStack VNF to dynamically configure itself based on meta data provided at deployment time

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#184]
Dynamically Cloud meta-data  configured IP router VNF for OpenStack
---

Goal:  The  VPP-based IP router cloud image should use meta data to configure it self dynamically
* independent of the orchestration/deployment tool used

This will make deployment of the tests cases, such as the [VNF router snake case](https://github.com/cncf/cnf-testbed/issues/175#issuecomment-462831993), more portable and cleaner.  

#### VNF is currently dynamically configured based on information from KVM including mac addresses.

Issues:
* NFVbench is currently configured to use the mac address of the ingress/egress of the VNF chain
* VPP in the VNF currently uses the mac addresses of other VNFs in the chain for routing traffic
* igb_uio kernel module used by [dpdk dev bind](https://github.com/cncf/cnf-testbed/blob/c828bed2940633314ea58e5c7d8ae22033875b07/comparison/kubecon18-chained_nf_test/VNF_openstack/shared/vEdge_vm_install.sh#L15) ([copied in the build from "somewhere"](https://github.com/cncf/cnf-testbed/commit/a04ef11db92c23d8d8773e387ec9dd97fcb227bb))

---

Tasks:
---
_Image and Multiple interfaces_
- [x] OpenStack image creation (see #175) 
- [x]  setup multiple interfaces with out hardcoding in the VNF
    - [x] [Create multiple ports from openstack cli with specified mac address and attach to the VM](https://github.com/cncf/cnf-testbed/issues/175#issuecomment-463025228) 
    - [x] [Setup the additional interfaces in the OS cloud-init ](https://github.com/cncf/cnf-testbed/issues/181#issuecomment-462973101)
- [x] Document what cluster to use for dev/testing
- [x] Document commands to create tenant network and servers via CLI in #175 and link here.
- [x] Create diagram showing interface connections from a VNF viewpoint for the chain used in #175

_VNF configuration_
- [x]  [Move IP and mac address items](https://github.com/cncf/cnf-testbed/blob/master/comparison/baseline_nf_performance-packet/vEdge/CNF/CSC_multichain_shared/base/configure.sh) out of NF configuration and provide as cloud meta-data
- [x] Create run_vsp.sh based on [run_csp.sh](https://github.com/cncf/cnf-testbed/blob/master/comparison/kubecon18-chained_nf_test/CNF/k8s/helm/run_csp.sh) to generate the values for the HEAT template used to deploy the VNF to OpenStack
    - [x] Set cores https://github.com/cncf/cnf-testbed/blob/master/comparison/baseline_nf_performance-packet/vEdge/CNF/CSC_multichain_shared/base/configure.sh#L314-L317
- [x] [VM configures VPP setup.gate based on cloud-init data](https://github.com/cncf/cnf-testbed/blob/master/comparison/baseline_nf_performance-packet/vEdge/VNF/VSC_multichain_shared/shared/configure.sh#L211-L243)

DEFERRED to post MWC
---

- Create a generic deploy_nf to instantiate a vm or deploy a container 
- Create a script or update deploy_nf to support deploying an entire chain 
- NSM will be stitching the network connections between containers

**Comment by taylor** [comment]
@taylor: will this support both IPv4 and IPv6?

@michaelspedersen: yes. the desired configuration can be chosen at deploy or run time.


Future: NF that supports both at the same time and directs traffic appropriately.  Multiple chains running with both types.

**Comment by michaelspedersen** [comment]
### Example of NF configuration (VPP, IPv4)

Below are examples showing the configuration that nodes will be using depending on the chain ID and the length of the chain. All examples will show two chains (IDs 1 and 2).
Anything marked in red is "dynamic", i.e. depends on the chain ID or the position in the chain.

---

**Chain Length 1**
![vpp_conf_1nodeness](https://user-images.githubusercontent.com/40474606/52785405-2f47ca00-3058-11e9-8401-d99a8b0db390.png)

---

**Chain Length 2**
![vpp_conf_2nodeness](https://user-images.githubusercontent.com/40474606/52785420-38389b80-3058-11e9-97b7-ff879ee9b5e9.png)

---

**Chain Length 3**
![vpp_conf_3nodeness](https://user-images.githubusercontent.com/40474606/52785433-4090d680-3058-11e9-831b-ddf828e163b0.png)

**Comment by taylor** [comment]
Reference #200 for updates on VM image
