### ISSUE TITLE
[Documentation] Add Roadmap.md for CNF Testbed

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#203]
[Documentation] Add Roadmap.md for CNF Testbed
---

Tasks: 

- [x]  create WIP spreadsheet for cnf-testbed > https://docs.google.com/spreadsheets/d/1X4ytlf7bbQ7TgwaCnilJkvQY8MucAegbgbifRHRp3vg/edit#gid=0
- [ ] update goals on spreadsheet
- [ ] create ROADMAP.md for cnf-testbed based on spreadsheet
