### ISSUE TITLE
EPIC: Adding external (PF/VF) connection to NSM Packet-Filtering example

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#248]
The existing use-case implementation for the NSM Packet-Filter ([Playbook](https://github.com/cncf/cnf-testbed/blob/master/comparison/ansible/deploy_nsm.yml), [Documentation](https://github.com/cncf/cnf-testbed/blob/master/docs/Deploy_K8s_CNF_Testbed.md#run-nsm-packet-filtering-example)) does not include external connectivity outside of the host.

This addition will add L2/3 connectivity to the `Gateway` service from an external host, as shown in the image below:
![nsm_pf_external](https://user-images.githubusercontent.com/40474606/63583056-85af3b80-c59a-11e9-9839-0bd0edca1ae0.PNG)

Steps to implement:
- [ ] Update playbook to collect facts from host
- [ ] Investigate how Mellanox ConnectX-4 can be utilized
  - Is it necessary to install OFED / RDMA in host ?
    - For PF and it necessary for additional VFs
    - VFs are not needed for this use-case, but will be needed for https://github.com/cncf/cnf-testbed/issues/249
  - Is it necessary to install OFED / RDMA in `Universal CNF` 
    - If this is needed, check if VPP in `Universal CNF` needs to be rebuilt with MLX support
- [ ] Update [gateway.yml](https://github.com/cncf/cnf-testbed/blob/master/comparison/ansible/roles/nsm_pf_cnf_install/files/packet-filtering/gateway.yaml) to support external connection (PF/VF)
  - [ ] Decide how to push necessary VPP init/startup configuration with PCI information to `gateway` service
    - Solution could be ConfigMap or directory volume mount
    - Either push full configuration file, or parse information provided through ConfigMap
  - [ ] Add additional configuration to `gateway.yml` to apply proper configuration to external interface
- [ ] Update or rework [check_packet_filtering.sh](https://github.com/cncf/cnf-testbed/blob/master/comparison/ansible/roles/nsm_pf_cnf_install/files/check_packet_filtering.sh) to add test for external connectivity
  - This will be running on a separate host, and can not be accessed using `kubectl` similar to what is done for the `client` services in the example.
  - It might require specifying an IP address of a server provisioned and configured manually (with correct subnet and VLANs)

**Comment by taylor** [comment]
Update VPP-CNF to support 0 or more physical devices in the helm chart.  

Eg.     ```  {{ .Values.phys_devs }}```

See
https://github.com/cncf/cnf-testbed/blob/a73eeafbf1eb2fe6f311fe259dc3ff129cb49c97/comparison/baseline_nf_performance-packet/host_vpp_container/helm/VPPcontainer/templates/configmap.yaml
