### ISSUE TITLE
Adding Multus to Kubernetes cluster

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#294]
As part of the [ROADMAP](https://github.com/cncf/cnf-testbed/blob/master/ROADMAP.md), the idea is to have a workload infrastructure example in CNF Testbed using [Multus](https://github.com/intel/multus-cni).

This task focuses on deploying Multus in an existing Kubernetes cluster deployed as part of the CNF Testbed. The more specific cases, e.g. utilizing [SRIOV CNI](https://github.com/intel/sriov-cni), will be handled through separate tasks.

**Tasks:**
- [x] Deploy Multus on CNF Testbed Kubernetes
  - [x] Use existing documentation to deploy Multus
  - [x] Test and verify functionality
- [x] Create workload infrastructure example in CNF Testbed
  - [x] Add yaml file(s) for basic deployment
  - [x] Add documentation on how to deploy and use
- [x] Create use-case for Multus
  - [x] Add yaml file(s) for basic use-case
  - [x] Add documentation on how to deploy and use

**Comment by michaelspedersen** [comment]
**Current status:**
Multus has been deployed using existing documentation. Everything seems to be running okay, but additional interfaces are not added to pods as expected.

A support ticket has been created on the Multus github page, which can be found [HERE](https://github.com/intel/multus-cni/issues/392)

**Comment by michaelspedersen** [comment]
Added support for installing Multus through Ansible and `examples/workload_infra`.
Documentation and use-case is still missing. Did a couple brief tests with CNI bridge (default) and macvlan, which both are working as expected.

The Multus deployment also prepares the node for SRIOV use-cases.

**Comment by michaelspedersen** [comment]
Example infra and use-case added. Still a simple example use-case, but I'd rather have that available for verification before creating more advanced cases with multiple infra tools (e.g. Multus + NSM)
