### ISSUE TITLE
Reference deployment of the GoGTP EPC user-plane using Docker

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#328]
### Reference deployment of the GoGTP EPC user-plane using Docker

The Docker reference deployment is a simplified version of the kubernetes GoGTP EPC user-plane. The deployment will use the default configurations for each part of the user-plane (see `examples/network_functions/go-gtp` in go-gtp branch), and network bridges created through Docker.

![image](https://user-images.githubusercontent.com/40474606/73653121-c1414c00-4688-11ea-8848-8f9c70af2f18.png)

**Tasks:**
- [x] Create network bridges for separating the different networks used in the EPC example (euu, s11, s1u, s1c, s5u, s5c, sgi)
- [x] Create containers needed for each of the GoGTP applications (eNB, MME, SGW, PGW)
- [x] Create containers for each of the endpoints (UE-Ext, SGI-Server)
- [x] Attach interfaces to containers with IP subnets matching the default default configurations already present in the images
- [x] Add README specifying how to run the GoGTP applications and test connectivity between endpoints

### Limitations

For this deployment the GoGTP applications are not started when the containers are initially brought up. As the interfaces are added after creating the containers, the applications will need to wait for this to happen prior to starting. This could be handled by adding pre-defined sleep states to each container, but for now everything will have to be started manually once the deploy script (`run_all.sh`) has finished. 

The endpoints are default Ubuntu 18.04 images, so before they can be used to test and verify traffic some manual installation and configuration is needed. The steps are doing this are included in the README file.
