### ISSUE TITLE
Update remaining images and use-cases (VPP and GoGTP)

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#348]
### Description
With the recent updates to vppcontainer (soelvkaer/vppcontainer) and GoGTP (soelvkaer/gogtp:*), there are still images and use-cases that needs to be updated.

### Relates issues/PRs/commits
#341 
#343 
https://github.com/cncf/cnf-testbed/commit/1aec3f728bf667ef5ae784a472eb0a56ebda7707

### Tasks
- [x] Update image for [rdma_vppcontainer](https://github.com/cncf/cnf-testbed/tree/master/examples/network_functions/rdma_vppcontainer)
- [x] Update image for [go-gtp-ubuntu](https://github.com/cncf/cnf-testbed/tree/master/examples/network_functions/go-gtp-ubuntu)
- [x] Update [k8s_bridged_cmk](https://github.com/cncf/cnf-testbed/tree/master/examples/use_case/gogtp-k8s/k8s_bridged_cmk) use-case that requires go-gtp-ubuntu (soelvkaer/gogtpu:*)
  - Do this once go-gtp-ubuntu has been updated

**Comment by michaelspedersen** [comment]
Images and use-cases updated and tested
